### ISSUE TITLE
Gosmee pod reports such error "No help topic for ..."

### ISSUE THREAD

**Issue by cmoulliard** [chmouel/gosmee#63]
## Issue

When we deploy `gosemee-client` as a pod

```
k get -n pipelines-as-code deployment/gosmee-client -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosmee-client
  namespace: pipelines-as-code
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gosmee-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gosmee-client
    spec:
      containers:
      - args:
        - https://smee.io/upi-0.apps.mystone.lab.upshift.rdu2.redhat.com
        - $(SVC)
        env:
        - name: SVC
          value: https://pipelines-as-code-controller-pipelines-as-code.apps.mystone.lab.upshift.rdu2.redhat.com/
        image: ghcr.io/chmouel/gosmee:main
        imagePullPolicy: IfNotPresent
        name: gosmee-client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
then the log reports
```
No help topic for 'https://smee.io/upi-0.apps.mystone.lab.upshift.rdu2.redhat.com'
```
